export default {
     perPage: ["10", "25", "50", "100"],
     pagination: {
          lastPage: "",
          currentPage: "",
          total: "",
          lastPageUrl: "",
          nextPageUrl: "",
          prevPageUrl: "",
          from: "",
          to: ""
     },
     TotalItemNotAvailable: 0,
     isModal: false,
     isLoading: false,
     isUpload: false,
     errors: {},
     priceCount: '',
     PriceChangeInfo: [],
     ItemsNotAvailable: [],
     Stores: [],
     Barangays: [],
     Towns: [],
     Provinces:[],
     Transportations: [],
     Departments: [],
     StoreHourList: [],
     Tenants:[],
     DCharges: [],
     filterTowns: [],
     filterBarangays: [],
     MinOrders:[],
     Users: [],
     UserTypes: [],
     Employees: [],
     Items: [],
     ItemCategory: [],
}